# config/packages/easy_admin.yaml
easy_admin:
  site_name:  'Ametix <em style="font-size: 80%;">CVthéque</em>'

  design:
    brand_color: '#936393'
    assets:
      favicon: '/bundles/easyadmin/img/favicon-32x32.png'
  entities:
  # change the following to the namespaces of your own entities
  - App\Entity\User